baseURL = 'jjasser.github.io'
languageCode = 'en-us'
title = 'Jacob J Blog'
theme = 'anatole'
summarylength = 10
enableEmoji = true


[params]
profilePicture = 'static/images/profile.jpg'
description = """
Call me Jo
Blogging from California
"""
displaymode = "dark"
# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true



[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"



