baseURL = "jjasser.github.io"
languageCode = "en-us"
title = "Jacob J Blog"
theme = "anatole"
summarylength = 10
enableEmoji = true


[params]
profilePicture = "/images/jacob.jpeg"
description = """
Blogging from California
"""
displaymode = "dark"
# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true


[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/jacobjasser/"


[menu]

  [[menu.main]]
  name = "HOME"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "ARCHIVE"
  weight = 200
  identifier = "archive"
  url = "/posts/"

  [[menu.main]]
  name = "ABOUT"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "CERTIFICATIONS"
  weight = 400
  identifier = "certifications"
  url = "/certifications/"

